#!/bin/bash
# grub2-unsign
# Unsigns every file in /boot. Depends on grub2-verify
# Author: Bandie Kojote
# Licence: GNU-GPLv3

if [[ "$@" == "-f" ]]
then
    printf '%s\n' "Skipping signature verification!!!" >&2
else
    # Check if something is wrong
    if ! grub-verify; then
        printf '%s\n' "grub2-verify has detected a one or more bad signatures." "Please check for malicious software before you're unsigning everything!" >&2
        exit 1
    fi
fi

# Then remove the signatures.
find /boot -name '*.sig' -exec rm -- '{}' +

echo "GRUB2 unsigned. WARNING: If you want to deactivate GRUB2's signature feature, change the check_signatures variable in the headers file!"
exit 0
